before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    main: ./main.go
    binary: purslane
    goos:
    - windows
    - darwin
    - linux
    ignore:
    - goos: darwin
      goarch: 386
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"

dockers:
  # Default, slim, no shell images 
  - goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    image_templates:
    - "levibostian/purslane:latest"
    - "levibostian/purslane:{{ .Major }}"
    - "levibostian/purslane:{{ .Major }}.{{ .Minor }}"
    - "levibostian/purslane:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
  # Alpine 
  - goos: linux
    goarch: amd64
    dockerfile: Dockerfile.alpine
    image_templates:
    - "levibostian/purslane:latest-alpine"    
    - "levibostian/purslane:{{ .Major }}-alpine"
    - "levibostian/purslane:{{ .Major }}.{{ .Minor }}-alpine"
    - "levibostian/purslane:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-alpine"
  
brews:
  - name: purslane
    github:
      owner: levibostian
      name: homebrew-tap
    folder: Formula
    homepage: "https://github.com/levibostian/purslane"

# snapcrafts:
#   - name: purslane
#     publish: true
#     summary: Scalable, flexible, affordable, and safe way to perform periodic tasks.
#     description: Run a single docker container inside of a cloud server as if it was a CLI.
#     grade: stable
#     confinement: strict
#     license: MIT
#     apps:
#       purslane:
#         plugs: ["home", "network", "config-file"]
#     plugs:
#       config-file:
#         interface: personal-files
#         read:      
#         - $HOME/.purslane

# skip changelog generation because semantic release does that for us already. Go releaser updates existing github releases if there is one.
changelog:
  skip: true 