language: go

go: 
  - 1.x

# https://github.com/aevea/commitsar/issues/230
git:
  depth: false

jobs:
  include:
    - stage: commit 
      script:
        # lint commits to make sure they are conventional 
        - curl -sf https://gobinaries.com/aevea/commitsar | sh; commitsar;
        # Test binaries can all build successfully 
        - curl -sL https://git.io/goreleaser | bash -s build --rm-dist --snapshot
    - stage: deploy
      script: 
        # Use nvm to install and use the Node LTS version (nvm is installed on all Travis images)
        - nvm install lts/*; npm i @semantic-release/git @semantic-release/changelog @semantic-release/exec; npx semantic-release;

stages:
  - name: commit
    if: type IN (push) AND tag IS blank
  - name: deploy
    if: type IN (push) AND branch IN (master, beta, alpha)